version: "2"
services:
  node1:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /Users/Francesco/Desktop/pg_rc:/home/node/app
    container_name: intro
    ports:
      - "8888:8888"
    expose:
      - 8888
    command: "npm run start"
  node2:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /Users/Francesco/Desktop/pg_rc:/home/node/app
    container_name: pubblica
    ports:
      - "3230:3230"
    expose:
      - 3230
    command: "npm run server"
  node3:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /Users/Francesco/Desktop/pg_rc:/home/node/app
    container_name: privata
    ports:
      - "2000:2000"
    expose:
      - 2000
    command: "npm run server2"
  
