version: "2"
services:
  node1:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/sveva/Desktop/University/RC/progetto/prova_docker:/home/node/app
    ports:
      - "8888:8888"
    expose:
      - 8888
    command: "npm run start"
  node2:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/sveva/Desktop/University/RC/progetto/prova_docker:/home/node/app
    ports:
      - "3230:3230"
    expose:
      - 3230
    command: "npm run server"
  node3:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/sveva/Desktop/University/RC/progetto/prova_docker:/home/node/app
    ports:
      - "2000:2000"
    expose:
      - 2000
    command: "npm run server2"
  
